#!/bin/bash
[[ "$(id -u)" -eq 0 ]] || (echo "FATAL: Root privilege is required."; exit 1)

FLAG_X86_64=`uname -a | grep x86_64 | wc -l`
CURRENT_IP=`ifconfig eth0 | grep -m 1 'inet addr:' | cut -d: -f2 | awk '{print $1}'`
UBUNTU_VERSION=`cat /etc/lsb-release | grep "DISTRIB_RELEASE" | awk '{split($0,a,"="); print a[2]}'`

if [[ "${UBUNTU_VERSION}" == "10.04" ]]; then
  echo "Ubuntu Lucid/10.04"
else
  echo "Ubuntu Precise/12.04"
fi

# Ubuntu Pre-Provisioning. // =============================================================
sed -i -e "s,kr\.archive\.ubuntu\.com,ftp\.daum\.net,g" /etc/apt/sources.list

# Add 10gen Repo  // =============================================================
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' \
  | sudo tee /etc/apt/sources.list.d/mongodb.list
  
apt-get update -fy
apt-get upgrade -fy
apt-get install -fy curl python-pip python-flask mongodb-10gen

sed -i -e "s,ftp\.daum\.net,kr\.archive\.ubuntu\.com,g" /etc/apt/sources.list


# Setup Environment // =============================================================
sed -i -e "s,\(TMOUT\)=.*,\1=0,g" /etc/bash.bashrc
locale-gen ko_KR.UTF-8
rm -f /root/.ssh/authorized_keys

# Config updater // =============================================================
wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/mongo-conf-set
chmod +x mongo-conf-set

cp mongo-conf-set /usr/bin/set-mongodb.conf
cp mongo-conf-set /usr/bin/set-mongos.conf
cp mongo-conf-set /usr/bin/set-mongoconfig.conf
rm -f mongo-conf-set

sed -i -e "s,\(/etc/mongodb\.conf\),/etc/mongos\.conf," /usr/bin/set-mongos.conf
sed -i -e "s,\(/etc/mongodb\.conf\),/etc/mongoconfig\.conf," /usr/bin/set-mongoconfig.conf

cp /etc/init.d/mongodb /etc/init.d/mongos
cp /etc/init.d/mongodb /etc/init.d/mongoconfig

cp /etc/mongodb.conf /etc/mongos.conf
cp /etc/mongodb.conf /etc/mongoconfig.conf

set-mongoconfig.conf dbpath "/var/lib/mongoconfig"
set-mongoconfig.conf logpath "/var/log/mongodb/mongoconfig.log"

sed -i -e "s,\(dbpath\),#\1," /etc/mongos.conf
set-mongos.conf logpath "/var/log/mongodb/mongos.log"

cat > /etc/init/mongos.conf << EOF
# Ubuntu upstart file at /etc/init/mongos.conf

limit nofile 20000 20000

kill timeout 300 # wait 300s between SIGTERM and SIGKILL.

pre-start script
    mkdir -p /var/log/mongodb/
end script

start on runlevel [2345]
stop on runlevel [06]

script
  ENABLE_MONGOS="yes"
  if [ -f /etc/default/mongodb ]; then . /etc/default/mongodb; fi
  if [ "x\$ENABLE_MONGOS" = "xyes" ]; then exec start-stop-daemon --start --quiet --chuid mongos --exec  /usr/bin/mongos -- --config /etc/mongos.conf; fi
end script
EOF

cat > /etc/init/mongoconfig.conf << EOF
# Ubuntu upstart file at /etc/init/mongoconfig.conf

limit nofile 20000 20000

kill timeout 300 # wait 300s between SIGTERM and SIGKILL.

pre-start script
    mkdir -p /var/lib/mongoconfig/
    mkdir -p /var/log/mongodb/
end script

start on runlevel [2345]
stop on runlevel [06]

script
  ENABLE_MONGOCONFIG="yes"
  if [ -f /etc/default/mongodb ]; then . /etc/default/mongodb; fi
  if [ "x\$ENABLE_MONGOCONFIG" = "xyes" ]; then exec start-stop-daemon --start --quiet --chuid mongoconfig --exec  /usr/bin/mongod -- --config /etc/mongoconfig.conf; fi
end script
EOF

# Install Mongo Service Utility
wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/mongo-service-conf
chmod +x mongo-service-conf
mv mongo-service-conf /usr/bin/mongo-service

# Disable All Service
mongo-service mongodb disable
mongo-service mongos disable
mongo-service mongoconfig disable


# Replicaset initiate utility
wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/mongo-replset
chmod +x mongo-replset
mv mongo-replset /usr/bin/mongo-replset
