#!/bin/bash

[[ "$(id -u)" -eq 0 ]] || (echo "FATAL: Root privilege is required."; exit 1)

FLAG_X86_64=`uname -a | grep x86_64 | wc -l`
CURRENT_IP=`ifconfig eth0 | grep -m 1 'inet addr:' | cut -d: -f2 | awk '{print $1}'`

# Centos Network ReConfigure // =============================================================
rm -f /etc/udev/rules.d/70-persistent-net.rules
sed -i -e "s,\(HWADDR.*\),#\1,g" /etc/sysconfig/network-scripts/ifcfg-eth0
/etc/init.d/network restart


# Centos TurnOff FireWall  // =============================================================
service iptables stop
chkconfig iptables off
service ip6tables stop
chkconfig ip6tables off


# Add 10gen Repo  // =============================================================
cat > /etc/yum.repos.d/mongodb.repo << EOF
[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1
EOF

yum update -y
yum install -y mongo-10gen mongo-10gen-server parted

# Python PIP // =============================================================
#wget http://peak.telecommunity.com/dist/ez_setup.py
#python ez_setup.py
#easy_install pip
#pip install flask
#yum install -y git


# Config updater // =============================================================
chkconfig --del mongod
cp -f /etc/mongod.conf /etc/mongodb.conf
cp -f /etc/init.d/mongod /etc/init.d/mongodb
sed -i -e "s,\(/etc/mongod\.conf\),/etc/mongodb\.conf," /etc/init.d/mongodb
sed -i -e "s,\(/var/lock/subsys/mongod\),/var/lock/subsys/mongodb," /etc/init.d/mongodb

cp -f /etc/mongod.conf /etc/mongos.conf
cp -f /etc/init.d/mongod /etc/init.d/mongos
sed -i -e "s,\(/etc/mongod\.conf\),/etc/mongos\.conf," /etc/init.d/mongos
sed -i -e "s,\(/var/lock/subsys/mongod\),/var/lock/subsys/mongos," /etc/init.d/mongos
sed -i -e "s,\(/usr/bin/mongod\),/usr/bin/mongos," /etc/init.d/mongos

cp -f /etc/mongod.conf /etc/mongoconfig.conf
cp -f /etc/init.d/mongod /etc/init.d/mongoconfig
sed -i -e "s,\(/etc/mongod\.conf\),/etc/mongoconfig\.conf," /etc/init.d/mongoconfig
sed -i -e "s,\(/var/lock/subsys/mongod\),/var/lock/subsys/mongoconfig," /etc/init.d/mongoconfig

rm -f /etc/mongod.conf
rm -f /etc/init.d/mongod

# Config updater // =============================================================
wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/mongo-conf-set
chmod +x mongo-conf-set

cp mongo-conf-set /usr/bin/set-mongodb.conf
cp mongo-conf-set /usr/bin/set-mongos.conf
cp mongo-conf-set /usr/bin/set-mongoconfig.conf
rm -f mongo-conf-set

sed -i -e "s,\(/etc/mongodb\.conf\),/etc/mongos\.conf," /usr/bin/set-mongos.conf
sed -i -e "s,\(/etc/mongodb\.conf\),/etc/mongoconfig\.conf," /usr/bin/set-mongoconfig.conf

wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/mongo-conf-unset
chmod +x mongo-conf-unset

cp mongo-conf-unset /usr/bin/unset-mongodb.conf
cp mongo-conf-unset /usr/bin/unset-mongos.conf
cp mongo-conf-unset /usr/bin/unset-mongoconfig.conf
rm -f mongo-conf-unset

sed -i -e "s,\(/etc/mongodb\.conf\),/etc/mongos\.conf," /usr/bin/unset-mongos.conf
sed -i -e "s,\(/etc/mongodb\.conf\),/etc/mongoconfig\.conf," /usr/bin/unset-mongoconfig.conf

set-mongoconfig.conf dbpath "/var/lib/mongoconfig"
set-mongoconfig.conf logpath "/var/log/mongo/mongoconfig.log"
set-mongoconfig.conf pidfilepath "/var/run/mongoconfig/mongoconfig.pid"

unset-mongos.conf dbpath
set-mongos.conf logpath "/var/log/mongo/mongos.log"
set-mongos.conf pidfilepath "/var/run/mongos/mongos.pid"

# Install Mongo Service Utility
wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/mongo-service-conf
chmod +x mongo-service-conf
mv mongo-service-conf /usr/bin/mongo-service

# Disable All Service
mongo-service mongodb disable
mongo-service mongos disable
mongo-service mongoconfig disable

# Replicaset initiate utility
wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/mongo-replset
chmod +x mongo-replset
mv mongo-replset /usr/bin/mongo-replset

# Shard initiate utility
wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/mongo-shard
chmod +x mongo-shard
mv mongo-shard /usr/bin/mongo-shard

# rc.local update
wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/rc.run_once
mv rc.run_once /etc/

sed -i -e "s,^\(exit\),#\1," /etc/rc.local
FLAG=`grep "rc.run_once" /etc/rc.local | wc -l`
if [[ "$FLAG" -eq 0 ]] ; then
  echo "/bin/bash /etc/rc.run_once" >> /etc/rc.local
fi

# Disk Expander / Mounter
wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/disk-mount
chmod +x disk-mount
mv disk-mount /usr/sbin/disk-mount

wget https://raw.github.com/ziozzang/mongodb-cloud-provisioning/master/src/lvm-attach-all
chmod +x lvm-attach-all
mv lvm-attach-all /usr/sbin/lvm-attach-all


rm -f /root/.ssh/authorized_keys
