#!/bin/bash
OS_DIST=`cat /etc/issue | head -n 1 | awk '{print $1}'`
# KT uCloudBiz
TARGET_DEVICE="/dev/xvd?"
TARGET_MOUNT_POINT=${TARGET_MOUNT_POINT:-"/data"}
TARGET_FILE_SYSTEM=${TARGET_FILE_SYSTEM:-"ext3"}
IDS=0

for disk in ${TARGET_DEVICE}
do
  # Check Already Partioned
  if [[ -e ${disk}1 ]]; then
    echo "==> ${disk}1 partition already exist"
    continue
  else
    let IDS=$IDS+1
    echo "==> ${disk} is not partioned"
    echo "==> Create MBR label"
    parted -s ${disk} mklabel msdos
    ncyl=$(parted ${disk} unit cyl print  | sed -n 's/.*: \([0-9]*\)cyl/\1/p')
    parted -a optimal ${disk} mkpart primary 0cyl ${ncyl}cyl
    /sbin/mkfs -t ${TARGET_FILE_SYSTEM} ${disk}1
    mkdir -p ${TARGET_MOUNT_POINT}${IDS}
    e2label ${disk}1 ${TARGET_MOUNT_POINT}${IDS}

    cat >> /etc/fstab << EOF
# Expand Area - ${disk}1 as ${TARGET_MOUNT_POINT}${IDS}
LABEL=${TARGET_MOUNT_POINT}${IDS}  ${TARGET_MOUNT_POINT}${IDS}  ${TARGET_FILE_SYSTEM}  defaults   1 2
EOF
    mount ${TARGET_MOUNT_POINT}${IDS}
  fi
done

# Exit Code will say how many partioned.
exit ${IDS}
