#!/bin/bash

SERVICE_NAME=${1?"Usage: $0 [service_name] (enable|disable)"}
FILE_NAME="/etc/init/${SERVICE_NAME}.conf"

case $SERVICE_NAME in
mongodb)
    ENV_NAME="ENABLE_MONGODB"
    ;;
mongos)
    ENV_NAME="ENABLE_MONGOS"
    ;;
mongoconfig)
    ENV_NAME="ENABLE_MONGOCONFIG"
    ;;
*)
    echo "unsupport service_name."
    exit 1
esac

COMMAND=${2?"Usage: $0 [service_name] (enable|disable)"}

case $COMMAND in
enable)
    if [ -f ${FILE_NAME} ]; then
        # For Ubuntu or upstart using linux system
        sed -i -e "s,\(${ENV_NAME}\)=.*,\1=\"yes\"," ${FILE_NAME}
    else
        # For Centos/RHEL
        chkconfig --add $1
    fi
    service $1 start
    ;;

disable)
    service $1 stop
    if [ -f ${FILE_NAME} ]; then
        # For Ubuntu or upstart using linux system
        sed -i -e "s,\(${ENV_NAME}\)=.*,\1=\"no\"," ${FILE_NAME}
    else
        # For Centos/RHEL
        chkconfig --del $1
    fi
    ;;

*)
    exit 1
esac
