#!/bin/bash

SERVICE_NAME=${1?"Usage: $0 [service_name] (enable|disable)"}
case $SERVICE_NAME in
mongodb)
    ENV_NAME="ENABLE_MONGODB"
    FILE_NAME=/etc/init/mongodb.conf
    ;;
mongos)
    ENV_NAME="ENABLE_MONGOS"
    FILE_NAME=/etc/init/mongos.conf
    ;;
mongoconfig)
    ENV_NAME="ENABLE_MONGOCONFIG"
    FILE_NAME=/etc/init/mongoconfig.conf
    ;;
*)
    echo "unsupport service_name."
    exit 1
esac

COMMAND=${2?"Usage: $0 [service_name] (enable|disable)"}

case $COMMAND in
enable)
    sed -i -e "s,\(${ENV_NAME}\)=.*,\1=\"yes\"," ${FILE_NAME}
    ;;

disable)
    sed -i -e "s,\(${ENV_NAME}\)=.*,\1=\"no\"," ${FILE_NAME}
    ;;

*)
    exit 1
esac
