#!/usr/bin/python
#
# MongoDB Shard Initiate script
# -- Code by Jioh L. jung (ziozzang@gmail.com)
#
# Usage [cmd] [shardname] [host1]...[hostn]
#       if host name is set to "self", it replace to ip_addr of eth0
#

import sys
import json
import os
import socket
import fcntl
import struct

def get_ip_address(ifname):
  s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  return socket.inet_ntoa(fcntl.ioctl(
        s.fileno(),
        0x8915,  # SIOCGIFADDR
        struct.pack('256s', ifname[:15])
    )[20:24])

def add_server_host(arr, host):
  if host.find("self") == 0:
    ip = get_ip_address("eth0")
    l = host.split(":")
    if len(l) > 1:
      host = "%s:%s" % (ip, l[1])
    else:
      host = "%s" % ip

  if len(arr) != 0:
    arr = "%s,%s" % (arr, host)
  else:
    arr = "%s" % host

  return arr

def make_command(arr, fn):
  o = open(fn, "w")
  o.write("use admin\n")
  o.write("db.runCommand(")
  o.write(json.dumps(arr))
  o.write(")\n")
  o.close()

if __name__ == '__main__':
  scrp = "/tmp/mongo-shardset.bash"
  fn = "/tmp/mongo-shardset.query"
  flog = "/tmp/mongo-shardset.log"
  log = "/var/log/mongo-shardset.log"

  port = "27017"

  if sys.argv[1][0:2] == "--":
    param = sys.argv[1][2:]
    parsed = param.split("=")
    if parsed[0] == "port":
      port = parsed[1]
      
    sys.argv = sys.argv[0:1] + sys.argv[2:]

  bs = ""
  for i in sys.argv[2:]:
    bs = add_server_host(bs, i)

  if sys.argv[1][0] == "-" or sys.argv[1][0] == "*":
    ns = "%s" % bs
  else:
    ns = "%s/%s" % (sys.argv[1], bs)
  asc = { "addshard" : ns }
  make_command(asc, fn)

  scriptsc = """#!/bin/bash
FN="{fn}"
FLOG="{flog}"
TLOG="{log}"
PORT="{port}"
cat $FN >> $TLOG
cat $FN | mongo --port $PORT > $FLOG  2>&1
CNT1=`grep -i "error" $FLOG | grep -i "connect" | wc -l`
CNT2=`tail -n 1 $FLOG | grep -i "bye" | wc -l`
N=1
while [ $N -lt 10 ] && [ $CNT1 -gt 0 ] || [ $N -lt 10 ] && [ $CNT2 -ne 1 ]
do
  sleep 5
  cat $FN | mongo --port $PORT > $FLOG  2>&1
  CNT1=`grep -i "error" $FLOG | grep -i "connect" | wc -l`
  CNT2=`tail -n 1 $FLOG | grep -i "bye" | wc -l`
  N=$[ N + 1 ]
done
cat $FLOG >> $TLOG
""".format(fn=fn,flog=flog,log=log,port=port)
  open(scrp,"w").write(scriptsc)
  os.system("bash %s" % scrp)
